services:
  energysmart-bridge:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WEBSERVER_PORT=8001
      - MQTT_SERVER=
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_PREFIX=energysmart
      - MQTT_DISCOVERY_PREFIX=homeassistant
    restart: unless-stopped
  energysmart-proxy:
    build: ./energysmart-proxy
    ports:
      - "443:443"
    restart: unless-stopped
