services:
  energysmart-bridge:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WEBSERVER_PORT=8001
      - MQTT_SERVER=192.168.0.45
      - MQTT_PORT=1883
      - MQTT_USERNAME=mqtt
      - MQTT_PASSWORD=mqtt1
      - MQTT_PREFIX=energysmart
      - MQTT_DISCOVERY_PREFIX=homeassistant
    restart: unless-stopped
  energysmart-proxy:
    build: ./energysmart-proxy
    ports:
      - "443:443"
    restart: unless-stopped
